---
# NGS Pipeline Configuration
# Flexible comparison specification for multi-condition experiments

project:
  name: "Deana_SF3B1_sDRIPEURNA"
  description: "NGS project with multiple treatments and controls"
  author: "srhartono@ucdavis.edu"
  date: "2025-09-29"

# Data organization
paths:
  data_dir: "data/Deana_SF3B1_sDRIPEURNA"
  results_dir: "results/Deana_SF3B1_sDRIPEURNA"
  notebooks_dir: "notebooks/Deana_SF3B1_sDRIPEURNA"
  references_dir: "references"

# Sample information
samples:
  treatments:
    - "SF3B102h"
    - "SF3B104h"
  controls:
    - "DMSO04h"
    - "SF3B100h"
  batches:
    - "240723"
    - "250717"
    - "250929"
  replicates: [1, 2]
  
# Assay types supported
assays:
  - "rnaseq"     # RNA sequencing
  - "euseq"      # EU-seq (nascent RNA)
  - "sdripseq"   # sDRIP-seq (RNA-DNA hybrids)
  - "endseq"     # ENDseq (5' end mapping)

# Comparison specifications
# Define which conditions to compare in differential analysis
comparisons:
  # Primary treatment vs control comparisons
  primary:
    - name: "Treat1_vs_Control"
      case: "Treat1"
      control: "Control"
      description: "Treatment 1 vs Control (all batches combined)"
      batch_effect: "include"

    - name: "Treat2_vs_Control"
      case: "Treat2"
      control: "Control"
      description: "Treatment 2 vs Control (all batches combined)"
      batch_effect: "include"

    - name: "Treat1_vs_Control1"
      case: "Treat1"
      control: "Control1"
      description: "Treatment 1 vs Control 1 (all batches combined)"
      batch_effect: "include"  # include, exclude, or batch_specific
      
    - name: "Treat2_vs_Control1"
      case: "Treat2"
      control: "Control1"
      description: "Treatment 2 vs Control 1 (all batches combined)"
      batch_effect: "include"

    - name: "Treat1_vs_Control2"
      case: "Treat1"
      control: "Control2"
      description: "Treatment 1 vs Control 2 (all batches combined)"
      batch_effect: "include"

    - name: "Treat2_vs_Control2"
      case: "Treat2"
      control: "Control2"
      description: "Treatment 2 vs Control 2 (all batches combined)"
      batch_effect: "include"


  # Cross-treatment comparisons
  cross_treatment:
    - name: "Treat1_vs_Treat2"
      case: "Treat1"
      control: "Treat2"
      description: "Treatment 1 vs Treatment 2 comparison"
      batch_effect: "include"
      
  # Cross-control comparisons
  cross_control:
    - name: "Control1_vs_Control2"
      case: "Control1"
      control: "Control2"
      description: "Control 1 vs Control 2 comparison"
      batch_effect: "include"

# Analysis parameters
analysis:
  differential_expression:
    method: "DESeq2"
    padj_threshold: 0.05
    lfc_threshold: 1.0
    
  peak_calling:
    method: "MACS2"
    qvalue_threshold: 0.05
    
  quality_control:
    min_reads: 1000000
    max_duplication_rate: 0.5
    min_mapping_rate: 0.7
    
# Resource allocation
resources:
  cpu_cores: 8
  memory_gb: 32
  disk_space_gb: 500

# Output preferences
output:
  generate_html_report: true
  create_browser_tracks: true
  export_expression_matrices: true
  generate_heatmaps: true
  create_volcano_plots: true